### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#10]
App crash after rotates sometime.

**Comment by cuongmanhvo162** [comment]
Thanks for report this. I just found out why it crash.

**Comment by cuongmanhvo162** [comment]
Hello there, I just fix and create an PR for this issue.

**Comment by cuongmanhvo162** [comment]
Hello there, I update master branch for the fix. Please review.

**Comment by thuypt** [comment]
App works well without any crash by rotating.
