### ISSUE TITLE
Naming convention is broken

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#11]
Some `private` method have `m` prefix, some not

**Comment by cuongmanhvo162** [comment]
Hello, could you point out private method without m prefix? If they are in package model/data, so the reason is. I think it would be better to keep the name of private properties of POJO just its name and without m prefix.

**Comment by thuypt** [comment]
`private method` without `m` prefix are in `model` as you said and follow POJO is OK, I will close this issue.
