### ISSUE TITLE
Swipe on main screen, app shows two loading dialogs

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#12]

**Comment by cuongmanhvo162** [comment]
Hello there, could you explain this issue more specific?

**Comment by thuypt** [comment]
When pull to refresh, screen show two loading process  
<img width="310" alt="screen shot 2560-12-19 at 12 27 49" src="https://user-images.githubusercontent.com/6264092/34142218-797b4a58-e4b8-11e7-8fc4-0454f44d1cda.png">

Do we need two loading processes to do the same action here?

Please mention me if my description is not clear enough.

**Comment by cuongmanhvo162** [comment]
Hello there, I just fix this issue. Please verify.

**Comment by thuypt** [comment]
It works well! I close this issue.

**Comment by cuongmanhvo162** [comment]
Hello there. I fix the issue. Now the app will prioritize the last action. That mean, the last action will be put on top of request queue.

For example:
- step 1: you swipe to refresh
- step 2: but you switch to another tab, the swipe to refresh request will be cancelled.

Or

- step 1: you scroll to the bottom list to load more data.
- step 2: but then you swipe to refresh, so the load more request will be cancelled. And the app will execute the swipe to refresh request.

**Comment by thuypt** [comment]
It works now. I will close this issue.
