### ISSUE TITLE
Recommend build flavor should config different between production and staging

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#13]
How to recognize an install version is production or staging? If they are the same, we will confuse, recommend  config different, for example suffix or prefix

**Comment by cuongmanhvo162** [comment]
Hello, I already have productFlavor defined in build.gradle file. Please could you clarify the meaning of suffix or prefix?

**Comment by thuypt** [comment]
I mean the current configuration of production and staging environment are the same, so after building a version app, how we can recognize it is `production` or `staging` version. I think better if we have some config like `versionNameSuffix` or `applicationIdSuffix`.

**Comment by cuongmanhvo162** [comment]
Hello there, my understanding is, you want to have version name or application id for the APK right?

**Comment by thuypt** [comment]
Yes, Could you please add these configs to the application?

**Comment by cuongmanhvo162** [comment]
Hello there, so the question is to recognize which version for production. With the current implementation. We have, first, with build flavor, we can choose the build variant, and we will have an debug apk with the name some thing like:

Choose debug variant
- app-staging-debug
- app-production-debug

Choose release variant
- app-staging-release
- app-production-release

Even if we generate the signed-build, we will have two folder, named production and staging with two apk.

Anyways, for more recognization, I update the name of the apk with "appname+versionCode+versionName)

**Comment by cuongmanhvo162** [comment]
Hello there, I update the master branch for the fix. Please review.

**Comment by thuypt** [comment]
Fixed in https://github.com/cuongmanhvo162/Nimbl3Assignment/commit/bd08fdc6cb8364dea29588fd152065378b4b7e11
