### ISSUE TITLE
Define a TAG for `Log` instead of use `string` directly

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#14]

**Comment by cuongmanhvo162** [comment]
Hello there, I remove unused import, remove Log with directly string.

**Comment by thuypt** [comment]
I still saw some unused import in the project, for example,`TimeUtil`, `SharedPreferenceHelper`, Could you please double check? And I reported unused import in #9 , so I will continue to follow #9 and close this one also.
