### ISSUE TITLE
Recommend using animation for collapse, expand for SORT BY view

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#16]

**Comment by cuongmanhvo162** [comment]
Hello, thanks for recommend this feature. Yes, I was actually think about it. I will make the app looks better.

**Comment by cuongmanhvo162** [comment]
Hello there, I just implement the animation for open and close Sort by view. Please review.

**Comment by thuypt** [comment]
A small thing is I think animation `500` is quite fast, because it has an effect to sake in the end already, so better if we multi 3/2 timeout. But your fixed is OK 👍 , enough for this issue, I will close this one.
