### ISSUE TITLE
Keep function small and preventing them from doing several different things

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#19]
It is better if you separate function and preventing them from doing several different things. It will be easier to read, test, debug. For example with this `TravelBookPresenterImpl` line 68

<img width="887" alt="screen shot 2560-12-18 at 11 34 54" src="https://user-images.githubusercontent.com/6264092/34090222-ff94bc7c-e3e7-11e7-8ff2-5604ea8eb241.png">

**Comment by cuongmanhvo162** [comment]
Hello, the function above do same logic and only affect to same view, so it could belong to one function.  Only create new function if it need to be called in several places.

Imagine if create a function to decide hide the swipe to refresh view, but it only be called when fetch new data not load more, so it will unnecessary. Also, checking is refresh or not must only in load function and should not be called from another method.

**Comment by thuypt** [comment]
<img width="875" alt="screen shot 2560-12-20 at 15 42 04" src="https://user-images.githubusercontent.com/6264092/34198370-c0285c72-e59c-11e7-9081-dc479253bc43.png">
It is a bigger method, too much condition and looks not nice after you added some logic, redundant one checked `responseData != null` also. Starting breaking your code down into well-named functions, it becomes a lot easier to read. 

Do you think we should refactor a little bit? Or no? Something like

 
```
...
.subscribe(responseData -> onDataResponse(isRefresh, responseData), error -> showEmpty());

private void onDataResponse(boolean isRefresh, TravelBooksResponseData responseData) {
        if (isRefresh) { // should we separate this to doSomethingWithRefresh(isRefresh)? 
            hideSwipeToRefresh();
        }
        if (isDataNotEmpty(responseData)) { // should we continue break to new function here?
            fetchData(responseData);
        } else {
            showEmpty();
        }
    }
```

**Comment by cuongmanhvo162** [comment]
Hello there. Yes you are right. The implementation now is actually more complicated than the beginning, and we should break down them into smaller methods for more readable.

So, based on this, I create two new private method for two main case. 
- The first one use for successful retrieve data from backend.
- The second use for failed retrieve data from the backend.

**Comment by thuypt** [comment]
How about reduce `displayDataList` to this:
```  
private void displayDataList(TravelBooksResponseData responseData, boolean isRefresh) {
        if (isRefresh) {
            mView.hideSwipeToRefresh();
        }
        // todo extras if conditions
        if (responseData != null && responseData.getTravelBooksData() != null && responseData.getTravelBooksData().size() > 0) {
            mView.fetchData(TravelBookUtil.getTravelBookDataWithUserData(responseData.getTravelBooksData(), responseData.getUserDataList()));
            updateMemoryCache(responseData.getTravelBooksData());
        } else {
            mView.showEmpty();
        }
    }```

**Comment by cuongmanhvo162** [comment]
Hello there, I agree with you, the modification will make the condition is more readable. Please review the pull request I made. Thank you.

**Comment by thuypt** [comment]
Actually, this function can continue to refactor. For now, It looks better so I will close this issue

**Comment by cuongmanhvo162** [comment]
Morning, yes I see. I think if we going to continue reformat these code, I think we can:
- create variable for getTravelBooksData, so we do not need to call response.getTravelBookData every single time.

Anyways, thanks for your advise, appreciate it.
