### ISSUE TITLE
Testing: missing some test case

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#20]
For example, don't have test for `loadMore`
Testing for presenter layer should coverage 100%, currently about 60%
 
<img width="511" alt="screen shot 2560-12-18 at 11 42 42" src="https://user-images.githubusercontent.com/6264092/34090418-62caa86e-e3e9-11e7-94dc-4cce1691b589.png">

**Comment by cuongmanhvo162** [comment]
Hello, I already have test for loadMore. 
You can find it named:
- testLoadMoreAndDisplayDataListSuccess
- testLoadMoreAndDisplayDataListFailedOrEmpty

For the test coverage in Presenter package, I admit that I have to do test another class in util package and scheduler package.

**Comment by thuypt** [comment]
I already saw `loadMore` test, sorry about that. 

The missed test case will be shown by IDE with pink color on the left side panel. It means these case is not tested yet. You can see the image below:
- Run coverage with `TravelBookPresenterTest` --> waiting for test complete, open `TravelBookPresenterImpl.java`

![screen shot 2560-12-18 at 17 51 25](https://user-images.githubusercontent.com/6264092/34102668-8a2a32c0-e41c-11e7-87c7-0e724cf8a07a.png)

**Comment by thuypt** [comment]
Please mention me when this issue is ready for review again.

**Comment by cuongmanhvo162** [comment]
Hello there, I just update master branch with the fix. Please review.

**Comment by thuypt** [comment]
Fixed in https://github.com/cuongmanhvo162/Nimbl3Assignment/commit/b86b1bd8302b6ffdcc702cacbd0e2953ba0cb36d
