### ISSUE TITLE
Recommend format project

### ISSUE THREAD

**Issue by thuypt** [cuongmanhvo162/Nimbl3Assignment#9]
* There are some redundant import, eg. `TravelBookPresenterImpl.java`
* Spacing, indent is broken, eg. `SharedPreferenceHelper` line 17
* Rearrange code block, for example `public` method should be before `private` method. eg. `ApiClient getInstance()`

**Comment by thuypt** [comment]
Have you resolved this issue? There is some redundant import, incorrect spacing and incorrect rearrange method. 

Please check project again, and the suggestion is you can use IDE format for easier.
* Right-click on Repo -> Reformat code

**Comment by cuongmanhvo162** [comment]
Morning there, I will going to use Reformat Code feature for each package, so that would be easier for manage the code changes.

Thanks for your advise.

**Comment by cuongmanhvo162** [comment]
Hello there, I just reformat the source code, remove unused imports. Please verify. Thanks.

**Comment by thuypt** [comment]
It looks good now 👍 , I will close this issue.
